# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

target 'iosApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'FlowStacks', '~> 0.3.6'
  pod 'ProgressIndicatorView', '~> 1.0'
  if ENV.include?("LOCAL_KOTLIN_PATH")
    pod 'shared', :path => ENV["LOCAL_KOTLIN_PATH"]
  else
    pod 'shared', '0.1'
  end

end
